version: 2
registries:
  nuget.org:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    registries: '*'