version: '3.4'

services:
  cicdtemplate.api:
    image: ${DOCKER_REGISTRY-}cicdtemplateapi
    container_name: CICDTemplate.Api
    build:
      context: .
      dockerfile: src/CICDTemplate.Api/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire.dashboard:18889
    networks:
      - otel

  cicdtemplate.db:
    image: postgres:latest
    container_name: CICDTemplate.Db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cicdtemplatedb
    networks:
      - otel

  aspire.dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: dashboard
    ports:
      - 18888:18888
    networks:
      - otel

networks:
  otel: