name: cn-ca build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore ./CICDTemplate.sln
    - name: Build
      run: dotnet build -c Release ./CICDTemplate.sln --no-restore
    - name: Test
      run: dotnet test -c Release ./CICDTemplate.sln --collect:"XPlat Code Coverage" --settings ./coverage.runsettings --no-build
    - name: Generate coverage report
      run: dotnet reportgenerator "-reports:./**/coverage.cobertura.xml" "-targetdir:./.coverage" -reporttypes:"Html_Dark;SonarQube"
    - name: Upload artifact for coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: .coverage
    - name: Create the package
      run: dotnet pack -c Release ./CICDTemplate.Template.csproj
    - name: Publish the package to GPR
      run: dotnet nuget push ./bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
